# Use root/example as user/password credentials
version: '3.1'

services:
  gateway:
    image: mozillaiot/gateway:latest
    restart: unless-stopped
    # "ports" are ignored because of "network_mode: host". Either use "ports"
    # or "network_mode: host".
    #ports:
    #  - "8080:8080"
    #  - "4443:4443"
    #network_mode: host
    ports:
      - 8080:8080
      - 4443:4443
    environment: 
      - "TZ=Canada/Toronto"
    volumes: 
      - c:\Users\mapei\docker\mozillaiot\gateway-docker\SharedData:/home/node/.mozilla-iot
    logging: 
      driver: "json-file"
      options: 
        max-size: "1m"
        max-file: "10"
    # If certain devices are needed, e.g. USB dongles, enable them here.
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/ttyACM0:/dev/ttyACM0
    # If Bluetooth, the container needs to run in privileged mode.
    #privileged: true
        
  db:
    image: mysql
   # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2205
      MYSQL_DATABASE: IOT
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 2205
    #persist data here
    volumes:
      - c:\Users\mapei\Onedrive\documents\docker\mysql80:/var/lib/mysql
    ports:
      - 3306:3306
  # grafana with mysql
  grafana:
    image:  grafana/grafana
    ports:
      - '3000:3000'
    environment: 
      GF_INSTALL_PLUGINS: percona-percona-app
  # tool to connect to mysql instance and allow prometheus to collect mysql stats
 
  # prometheus stores and handle time series data for stats around mysql
  #prometheus:
  #  image:  prom/prometheus
  #  volumes:
  #    - ./promethues:/etc/prometheus
  #  links:
  #    - prom_mysql_exporter
  #  ports:
  #    - 9090



   #adminer:
   #restart: always
    ## note the port mapping , 8080 is already used by gateway so we use 3306
    #ports:
    # - 3306:8080
     